sudo: false
dist: precise
language: php
matrix:
  fast_finish: true
  include:
    - php: 5.3.3
  allow_failures:
    - php: nightly
      env: OPTIMIZE=1
    - php: hhvm
      env: OPTIMIZE=1
branches:
  except:
    - /^dist/
    - /^release/
before_script:
  - ./scripts/travis/setup.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php -i; fi"
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh